linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 200
    statements: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow # not important for now
      - unnamedResult # not important
  gocyclo:
    min-complexity: 15
  goimports: {}
  revive:
    confidence: 0
  gofmt:
    simplify: true
  mnd:
    # don't include the "operation" and "assign"
    checks: [argument, case, condition, return]
  govet:
    settings:
      printf:
        funcs:
          - (github.com/jenkins-x/jx-logging/v3/pkg/log/Logger()).Debugf
          - (github.com/jenkins-x/jx-logging/v3/pkg/log/Logger()).Infof
          - (github.com/jenkins-x/jx-logging/v3/pkg/log/Logger()).Warnf
          - (github.com/jenkins-x/jx-logging/v3/pkg/log/Logger()).Errorf
          - (github.com/jenkins-x/jx-logging/v3/pkg/log/Logger()).Fatalf
  lll:
    line-length: 140
  misspell: {}
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - errcheck
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - revive
    - gocritic
    - govet

run:
  timeout: 1h30m
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
